Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
image = io.imread('camera.png')
plt.imshow(image, cmap='gray')
plt.axis('off')
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m image [38;5;241m=[39m [43mio[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mcamera.png[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m      2[0m plt[38;5;241m.[39mimshow(image, cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mgray[39m[38;5;124m'[39m)
[1;32m      3[0m plt[38;5;241m.[39maxis([38;5;124m'[39m[38;5;124moff[39m[38;5;124m'[39m)

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skimage/io/_io.py:53[0m, in [0;36mimread[0;34m(fname, as_gray, plugin, **plugin_args)[0m
[1;32m     50[0m         plugin [38;5;241m=[39m [38;5;124m'[39m[38;5;124mtifffile[39m[38;5;124m'[39m
[1;32m     52[0m [38;5;28;01mwith[39;00m file_or_url_context(fname) [38;5;28;01mas[39;00m fname:
[0;32m---> 53[0m     img [38;5;241m=[39m [43mcall_plugin[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mimread[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mfname[49m[43m,[49m[43m [49m[43mplugin[49m[38;5;241;43m=[39;49m[43mplugin[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mplugin_args[49m[43m)[49m
[1;32m     55[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m(img, [38;5;124m'[39m[38;5;124mndim[39m[38;5;124m'[39m):
[1;32m     56[0m     [38;5;28;01mreturn[39;00m img

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skimage/io/manage_plugins.py:205[0m, in [0;36mcall_plugin[0;34m(kind, *args, **kwargs)[0m
[1;32m    202[0m     [38;5;28;01mexcept[39;00m [38;5;167;01mIndexError[39;00m:
[1;32m    203[0m         [38;5;28;01mraise[39;00m [38;5;167;01mRuntimeError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124mCould not find the plugin [39m[38;5;124m"[39m[38;5;132;01m{[39;00mplugin[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m for [39m[38;5;132;01m{[39;00mkind[38;5;132;01m}[39;00m[38;5;124m.[39m[38;5;124m'[39m)
[0;32m--> 205[0m [38;5;28;01mreturn[39;00m [43mfunc[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/skimage/io/_plugins/imageio_plugin.py:11[0m, in [0;36mimread[0;34m(*args, **kwargs)[0m
[1;32m      9[0m [38;5;129m@wraps[39m(imageio_imread)
[1;32m     10[0m [38;5;28;01mdef[39;00m [38;5;21mimread[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m---> 11[0m     out [38;5;241m=[39m np[38;5;241m.[39masarray([43mimageio_imread[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m)
[1;32m     12[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m out[38;5;241m.[39mflags[[38;5;124m'[39m[38;5;124mWRITEABLE[39m[38;5;124m'[39m]:
[1;32m     13[0m         out [38;5;241m=[39m out[38;5;241m.[39mcopy()

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/imageio/v3.py:53[0m, in [0;36mimread[0;34m(uri, index, plugin, extension, format_hint, **kwargs)[0m
[1;32m     50[0m [38;5;28;01mif[39;00m index [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:
[1;32m     51[0m     call_kwargs[[38;5;124m"[39m[38;5;124mindex[39m[38;5;124m"[39m] [38;5;241m=[39m index
[0;32m---> 53[0m [38;5;28;01mwith[39;00m [43mimopen[49m[43m([49m[43muri[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mplugin_kwargs[49m[43m)[49m [38;5;28;01mas[39;00m img_file:
[1;32m     54[0m     [38;5;28;01mreturn[39;00m np[38;5;241m.[39masarray(img_file[38;5;241m.[39mread([38;5;241m*[39m[38;5;241m*[39mcall_kwargs))

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/imageio/core/imopen.py:113[0m, in [0;36mimopen[0;34m(uri, io_mode, plugin, extension, format_hint, legacy_mode, **kwargs)[0m
[1;32m    111[0m     request[38;5;241m.[39mformat_hint [38;5;241m=[39m format_hint
[1;32m    112[0m [38;5;28;01melse[39;00m:
[0;32m--> 113[0m     request [38;5;241m=[39m [43mRequest[49m[43m([49m[43muri[49m[43m,[49m[43m [49m[43mio_mode[49m[43m,[49m[43m [49m[43mformat_hint[49m[38;5;241;43m=[39;49m[43mformat_hint[49m[43m,[49m[43m [49m[43mextension[49m[38;5;241;43m=[39;49m[43mextension[49m[43m)[49m
[1;32m    115[0m source [38;5;241m=[39m [38;5;124m"[39m[38;5;124m<bytes>[39m[38;5;124m"[39m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(uri, [38;5;28mbytes[39m) [38;5;28;01melse[39;00m uri
[1;32m    117[0m [38;5;66;03m# fast-path based on plugin[39;00m
[1;32m    118[0m [38;5;66;03m# (except in legacy mode)[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/imageio/core/request.py:247[0m, in [0;36mRequest.__init__[0;34m(self, uri, mode, extension, format_hint, **kwargs)[0m
[1;32m    244[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mInvalid Request.Mode: [39m[38;5;132;01m{[39;00mmode[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    246[0m [38;5;66;03m# Parse what was given[39;00m
[0;32m--> 247[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_parse_uri[49m[43m([49m[43muri[49m[43m)[49m
[1;32m    249[0m [38;5;66;03m# Set extension[39;00m
[1;32m    250[0m [38;5;28;01mif[39;00m extension [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/imageio/core/request.py:382[0m, in [0;36mRequest._parse_uri[0;34m(self, uri)[0m
[1;32m    380[0m         fn [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_filename_zip[[38;5;241m0[39m]
[1;32m    381[0m     [38;5;28;01mif[39;00m ([38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists(fn)) [38;5;129;01mand[39;00m (fn [38;5;129;01min[39;00m EXAMPLE_IMAGES):
[0;32m--> 382[0m         [38;5;28;01mraise[39;00m [38;5;167;01mIOError[39;00m(
[1;32m    383[0m             [38;5;124m"[39m[38;5;124mNo such file: [39m[38;5;132;01m%r[39;00m[38;5;124m. This file looks like one of [39m[38;5;124m"[39m
[1;32m    384[0m             [38;5;124m"[39m[38;5;124mthe standard images, but from imageio 2.1, [39m[38;5;124m"[39m
[1;32m    385[0m             [38;5;124m"[39m[38;5;124mstandard images have to be specified using [39m[38;5;124m"[39m
[1;32m    386[0m             [38;5;124m'[39m[38;5;124m"[39m[38;5;124mimageio:[39m[38;5;132;01m%s[39;00m[38;5;124m"[39m[38;5;124m.[39m[38;5;124m'[39m [38;5;241m%[39m (fn, fn)
[1;32m    387[0m         )
[1;32m    389[0m [38;5;66;03m# Make filename absolute[39;00m
[1;32m    390[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_uri_type [38;5;129;01min[39;00m [URI_FILENAME, URI_ZIPPED]:

[0;31mOSError[0m: No such file: 'camera.png'. This file looks like one of the standard images, but from imageio 2.1, standard images have to be specified using "imageio:camera.png".

